FROM debian:bullseye-slim

WORKDIR /usr/local/lib/mlshapes/
RUN apt update && apt -y upgrade 
RUN apt install -y build-essential libssl-dev python3-dev python3 \
python3-pip python3-venv 

COPY * /usr/local/lib/mlshapes/
COPY lib/Algo.py lib/
COPY shapes/* shapes/

RUN pip3 install opencv-python websockets imutils rpyc
    
CMD "/usr/local/lib/mlshapes/docker-osx.sh" 

